#!/bin/bash
# install.sh
# Claude Code Slack Status Integration のセットアップ
# statusline-command.sh にフックを追加し、レート制限を Slack ステータスに反映する

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "=== Claude Code Slack Status Installer ==="
echo ""

# =========================================================
# 前提条件チェック
# =========================================================
for cmd in jq curl; do
    if command -v "$cmd" >/dev/null 2>&1; then
        echo "[OK] $cmd found"
    else
        echo "[NG] $cmd is required. Please install it first."
        exit 1
    fi
done

# =========================================================
# SLACK_USER_TOKEN チェック
# =========================================================
if [ -f "$PROJECT_DIR/.env" ]; then
    if grep -q '^SLACK_USER_TOKEN=' "$PROJECT_DIR/.env" 2>/dev/null; then
        echo "[OK] SLACK_USER_TOKEN found in .env"
    else
        echo ""
        echo "[!!] SLACK_USER_TOKEN が .env に見つかりません。"
        echo "     以下を .env に追加してください:"
        echo ""
        echo "     SLACK_USER_TOKEN=xoxp-your-token-here"
        echo ""
        echo "     必要な OAuth スコープ: users.profile:write"
        echo ""
        read -r -p "     続行しますか？ (y/N): " confirm
        if [[ ! "$confirm" =~ ^[yY]$ ]]; then
            echo "中断しました。"
            exit 1
        fi
    fi
else
    echo "[!!] .env が見つかりません: $PROJECT_DIR/.env"
    echo "     インストール後に SLACK_USER_TOKEN を設定してください。"
fi

# =========================================================
# Config 作成（特殊文字に安全な方式）
# =========================================================
CONFIG_DIR="${HOME}/.config/claude-slack-status"
mkdir -p "$CONFIG_DIR"

{
    echo "# Claude Code Slack Status Config"
    echo "# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "# mugi-claw プロジェクトディレクトリ（.env の読み込み元）"
    printf 'MUGI_CLAW_DIR=%s\n' "$PROJECT_DIR"
    echo ""
    echo "# 更新間隔（秒）: 5分 = 300"
    echo "UPDATE_INTERVAL=300"
} > "$CONFIG_DIR/config"
echo "[OK] Config: $CONFIG_DIR/config"

# =========================================================
# スクリプトをインストール
# =========================================================
HOOKS_DIR="${HOME}/.claude/hooks/scripts"
mkdir -p "$HOOKS_DIR"

cp "$SCRIPT_DIR/update-slack-status.sh" "$HOOKS_DIR/"
chmod +x "$HOOKS_DIR/update-slack-status.sh"
echo "[OK] Script: $HOOKS_DIR/update-slack-status.sh"

# =========================================================
# キャッシュディレクトリ作成
# =========================================================
mkdir -p /tmp/claude
echo "[OK] Cache dir: /tmp/claude"

# =========================================================
# statusline-command.sh にパッチ適用
# =========================================================
STATUSLINE="${HOME}/.claude/statusline-command.sh"
MARKER="# >>> SLACK STATUS UPDATE >>>"

if [ -f "$STATUSLINE" ]; then
    if grep -q "$MARKER" "$STATUSLINE"; then
        echo "[OK] statusline already patched (skip)"
    else
        cat >> "$STATUSLINE" << 'PATCH_EOF'

# >>> SLACK STATUS UPDATE >>>
# Slack ユーザーステータスにレート制限情報を反映（5分間隔・バックグラウンド）
(~/.claude/hooks/scripts/update-slack-status.sh &) 2>/dev/null
# <<< SLACK STATUS UPDATE <<<
PATCH_EOF
        echo "[OK] statusline patched: $STATUSLINE"
    fi
else
    echo "[!!] statusline not found: $STATUSLINE"
    echo "     手動で以下を statusline スクリプトに追加してください:"
    echo '     (~/.claude/hooks/scripts/update-slack-status.sh &) 2>/dev/null'
fi

# =========================================================
# 完了
# =========================================================
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Slack ステータスは Claude Code 使用中に5分間隔で更新されます。"
echo ""
echo "表示例: 5h: 45.0% (reset 14:30) | 7d: 20.0%"
echo ""
echo "手動テスト:"
echo "  ~/.claude/hooks/scripts/update-slack-status.sh"
echo ""
echo "ログ確認:"
echo "  cat /tmp/claude/slack-status.log"
echo ""
echo "アンインストール:"
echo "  bash $SCRIPT_DIR/uninstall.sh"
